2021-09-15 23:57:11,356-[operateConfigData.py]-Line: 25 INFO: 文件：browser.ini 检索成功，正在获取文件中数据，请稍后...
2021-09-15 23:57:12,861-[browser.py]-Line: 51 INFO: 正在打开：Chrome 浏览器...
2021-09-15 23:57:12,862-[browser.py]-Line: 56 INFO: 设置隐式等待：10s
2021-09-15 23:57:12,980-[browser.py]-Line: 154 INFO: 当前浏览器窗口最大化
2021-09-15 23:57:16,665-[browser.py]-Line: 112 INFO: 当前窗口打开地址：http://www.baidu.com
2021-09-15 23:57:27,700-[decorator.py]-Line: 32 ERROR: 
Traceback (most recent call last):
  File "E:\MY_PROJECT\my_project\DDT_FrameWork\common\tools\decorator.py", line 30, in inner
    func(*args, **kwargs)
  File "E:\MY_PROJECT\my_project\DDT_FrameWork\common\seleniumLibrary\input.py", line 25, in input
    self._find_element(elementPath).send_keys(value)
  File "E:\MY_PROJECT\my_project\DDT_FrameWork\common\seleniumLibrary\find.py", line 27, in _find_element
    self.wait_visibility_of_element(elementPath)
  File "E:\MY_PROJECT\my_project\DDT_FrameWork\common\seleniumLibrary\wait.py", line 50, in wait_visibility_of_element
    message)
  File "D:\python\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 当前页面中 10s 内没有找到或不可见对应元素：('id', 'kw0') ！！！


